# Generated by Django 4.0.6 on 2022-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTrackModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenlogo', models.URLField()),
                ('tokennames', models.CharField(max_length=2000)),
                ('tokenprice', models.FloatField()),
            ],
        ),
    ]
